# Generated by Django 3.0.8 on 2020-08-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200801_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='pizza',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
