# Generated by Django 3.0.8 on 2020-08-13 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200813_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='subtotal',
            new_name='price',
        ),
    ]
