# Generated by Django 3.0.8 on 2020-08-21 01:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200817_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sicilian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64)),
                ('pizza_size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=64)),
                ('num_toppings', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(4)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
