# Generated by Django 3.0.8 on 2020-08-21 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_sicilian'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sicilian',
            old_name='pizza_size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='sicilian',
            old_name='num_toppings',
            new_name='toppings',
        ),
    ]
