# Generated by Django 3.0.8 on 2020-08-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200821_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='receipt',
        ),
    ]
